### ISSUE TITLE
Remove --arch option

### ISSUE THREAD

**Issue by atreyasha** [pbrisbin/downgrade#106]
Because only `x86_64` and `any` architecture types exist in the ALA, we can remove the `--arch` option and any corresponding logic.

**Comment by atreyasha** [comment]
@pbrisbin do you want to have this fixed before releasing? If so, what should the two options be?

As per my understanding, the ALA only offers `x86_64` and `any` options for architectures. I could not find `i686` options and they are only present in old mirrors such as such as this: https://ia801003.us.archive.org/24/items/archlinux_pkg_xorg-twm/

**Comment by pbrisbin** [comment]
I won't block release for this. I actually forget, are we waiting on anything or should I pull that trigger?

The architecture option is actually super duper old, from a time when `x86_64` vs `i686` actually mattered and you had to look for correct packages. If there are only `x86_63` or `any` packages available presently, I think we should remove this option and any logic related to it. We should just include all packages in the output all the time, since they're all valid packages for your system.

**Comment by atreyasha** [comment]
> I won't block release for this. I actually forget, are we waiting on anything or should I pull that trigger?

We are done, so we can release anytime.

> The architecture option is actually super duper old, from a time when `x86_64` vs `i686` actually mattered and you had to look for correct packages. If there are only `x86_64` or `any` packages available presently, I think we should remove this option and any logic related to it. We should just include all packages in the output all the time, since they're all valid packages for your system.

Ah I see. Yes true so now the `--arch` option is redundant. I will change this issue to removing the `--arch` option for the next iteration after we release this one.

**Comment by pbrisbin** [comment]
Awesome. v6.3.0 just released, :tada:

**Comment by pbrisbin** [comment]
Closed by #116.
