### ISSUE TITLE
Ignore List Problem

### ISSUE THREAD

**Issue by pjpreilly** [pbrisbin/downgrade#53]
When an item is added to the ignore list by answering "y" after downgrading, it is placed into /etc/pacman.conf at the bottom of the ignore list (with others commented above it). When this occurs the pamac preference/General is unable to remove the item with the highlight & "-" function. The only way to remove it is to edit /etc/pacman.conf with root privileges & remove it. When an item is added to the ignore list directly in this preference panel it is placed at the TOP of the list as is able to be removed successfully.

**Comment by pbrisbin** [comment]
Could you please provide your full `/etc/pacman.conf` from before and after answering `y` and having an item appending in the incorrect place?

**Comment by pjpreilly** [comment]
3 files included. No ignore, ignore by downgrade & ignore by pamac. When downgrade updates the file pamac cannot remove it in the preferences.

[pacman-no-ignore.conf.txt](https://github.com/pbrisbin/downgrade/files/836089/pacman-no-ignore.conf.txt)
[pacman-pamac.conf.txt](https://github.com/pbrisbin/downgrade/files/836090/pacman-pamac.conf.txt)
[pacman-downgrade.conf.txt](https://github.com/pbrisbin/downgrade/files/836091/pacman-downgrade.conf.txt)

**Comment by pbrisbin** [comment]
Thanking you for supplying those. `downgrade` creating content like this:

```
#IgnorePkg   =
IgnorePkg = kodi
#IgnoreGroup =
```

It not expected. The code _intends_ to create content like this:

```
IgnorePkg = kodi
#IgnoreGroup =
```

So that is a bug that I can fix.

That said, the "wrong" form is completely valid syntax, so pamac (whatever that is) not being able to handle it is a bug in _that_ tool, which you may want to report.

**Comment by pbrisbin** [comment]
> downgrade creating content like this ... is not expected

I'm sorry, I just want back to the code and that is actually intentional. It makes it easier to undo the changes by leaving the commented line above the newly introduced line. Since that is perfectly valid syntax for that configuration file, there is no bug here in downgrade. The only bug is in pamac.

**Comment by pjpreilly** [comment]
Maybe you can report it since it breaks downgrade.

**Comment by pbrisbin** [comment]
How is downgrade broken?

**Comment by pjpreilly** [comment]
I know not to add ignore after using downgrade because I can't remove it unless I edit pcman.conf

**Comment by pbrisbin** [comment]
Sorry, I disagree that that's breakage in downgrade. 

> I can't remove it unless I edit pcman.conf

That is because the method you prefer to use to interact with pacman configuration is pamac, and it is broken.

**Comment by pjpreilly** [comment]
pamac uses & maintains the commented ignore line which is in pacman.conf by default. I suggest that downgrade should do the same.

**Comment by pbrisbin** [comment]
Thank you for the suggestion, I will consider it.
