### ISSUE TITLE
Show date-stamps in the package version list

### ISSUE THREAD

**Issue by Xavion** [pbrisbin/downgrade#58]
It would be good to have the creation/upload date listed next to each entry in the list. If I want to roll back to a package I know I installed two Saturdays ago (but don't remember the version number), I have to go by its date-stamp.

See my comments from the June of 2017 on the ['downgrade' AUR webpage](https://aur.archlinux.org/packages/downgrade/) for more information.

**Comment by pbrisbin** [comment]
FWIW, I think this could be better handled by a separate tool that answers "what version did I install/update at X time". Then `downgrade` remains simply version-based. My other tool [`wat`](https://github.com/pbrisbin/wat) comes close to that. Maybe it, or something like it, could be built to output `package-version` which you could even feed right to `downgrade`.

**Comment by Xavion** [comment]
OK, sounds good.  While we're there, can you get 'wat' to print the date/time of each upgrade?  I don't want to have to try and remember that "wat 3" occurred 2.5 weeks ago.  Either that or just add a '-t' flag which prints the timestamps of the 10 most recent upgrades.

**Comment by pbrisbin** [comment]
> Either that or just add a '-t' flag which prints the timestamps of the 10 most recent upgrades.

You nerd-sniped me. I've added an option to include the timestamps of the log messages that `wat` prints. So you should get this behavior with `wat -t 10` now.

I'm going to close this issue, not because I think my improvements to `wat` meet your needs exactly, but because whatever future work happens in this area won't be done on `downgrade`.
