### ISSUE TITLE
Can't downgrade linux kernel and linux headers -> Outsource URL redirect from pacman to downgrade?

### ISSUE THREAD

**Issue by Yves0** [pbrisbin/downgrade#94]
I have to copy the url and download them with wget.

then I found that the urls were redirected

https://archive.archlinux.org/packages/l/linux-headers/linux-headers-5.5.10.arch1-1-x86_64.pkg.tar.zst
->
https://ia601007.us.archive.org/19/items/archlinux_pkg_linux/linux-5.5.10.arch1-1-x86_64.pkg.tar.zst

**Comment by pbrisbin** [comment]
Hmm, `downgrade` just calls `pacman -U <url>`. I wonder if it's a better feature request for `pacman`, to handle any redirects in `-U` (like `curl -L`)? Otherwise, `downgrade` would either need to make a (usually) unnecessary HTTP request to figure out the URL, or just take over ownership of downloading (with `curl -L`) and passing a file to `pacman -U`. Not terrible, but not ideal.

**Comment by atreyasha** [comment]
Btw @pbrisbin, should we close this issue since this is more relevant to `pacman`?

Also, I would probably take time off the open issues as I need to catch up with some work. Will try to push some updates whenever I can squeeze in some time.

**Comment by pbrisbin** [comment]
I'm fine with closing this, but more because it's stale since the reporting hasn't responded. If it's more relevant to `pacman` or not is still an open question, IMO.
